name: Run Ansible Playbook

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install ansible passlib

      - name: Run Ansible Playbook
        run: |
          ansible-playbook DevOps/Ansible/PlaybookLinux.yaml -i localhost, --extra-vars "ansible_connection=local"
