name: Run Ansible Playbook

on:
  workflow_dispatch:  # Cela permet de déclencher manuellement le workflow
    inputs:
      environment:
        description: 'Ansible'
        required: true
        default: 'Playbook'

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          sudo apt-get install passlib
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook DevOps/Ansible/PlaybookLinux.yaml -i localhost, --extra-vars "ansible_connection=local"